{% set name = "apache-airflow-providers-papermill" %}
{% set version = "3.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_papermill-{{ version }}.tar.gz
  sha256: 7f23c938895a2e0f601aa9bc918f0f3c94b7bfb3454ee06a23f1d050851842c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow >=2.8.0
    - ipykernel
    - pandas >=2.1.2,<2.2
    - papermill >=2.6.0

    # papermill[all]
    - azure-datalake-store >=0.0.30
    - azure-storage-blob >=12.1.0
    - requests >=2.21.0
    - azure-identity >=1.3.1
    - gcsfs >=0.2.0
    - pygithub >=1.55
    - pyarrow >=2.0
    - boto3
    - black >=19.3b0

    - scrapbook
    # scrapbook[all] just requires papermill[all] so we're good

test:
  imports:
    - airflow.providers.papermill
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-papermill for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/papermill/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-papermill/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
