{% set name = "apache-airflow-providers-papermill" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-papermill-{{ version }}.tar.gz
  sha256: ba4ab29ae922babe4e42fb9ecb3dc2f9fed01cf5c05942ac1727f1963478bc9a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - apache-airflow >=2.2.0
    - papermill >=1.2.1
    # papermill[all]
    - azure-datalake-store >=0.0.30
    - azure-storage-blob >=12.1.0
    - requests >=2.21.0
    - gcsfs >=0.2.0
    - pyarrow
    - boto3
    
    - scrapbook
    # scrapbook[all] just requires papermill[all] so we're good

test:
  imports:
    - airflow.providers.papermill
    - airflow.providers.papermill.operators
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-papermill package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-papermill/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
