{% set name = "apache-airflow-providers-papermill" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-papermill-{{ version }}.tar.gz
  sha256: d6713f010c35d38fb27a4193ae88c97f170eeb775182a5df593fbbe0373d0206

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - apache-airflow >=2.1.0
    # note: this is just the base papermill, not papermill[all] that it should be
    - papermill >=1.2.1
    # note: this is just the base scrapbook, not scrapbook[all] that it should be
    - scrapbook

test:
  imports:
    - airflow.providers.papermill
    - airflow.providers.papermill.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Papermill for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-papermill/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
