{% set name = "apache-airflow-providers-papermill" %}
{% set version = "3.11.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_papermill-{{ version }}.tar.gz
  sha256: 589b63b2266f600624a5005b935426d95f3737feb1f4e9c0ed23bf9c5db5911e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    - apache-airflow-providers-common-compat >=1.8.0
    - papermill >=2.6.0
    - scrapbook >=0.5.0
    - ipykernel >=6.29.4
    # more restrictive for python >=3.13
    - pandas >=2.2.3
    - nbconvert >=7.16.1

test:
  imports:
    - airflow.providers.papermill
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-papermill for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-papermill/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
