{% set name = "apache-airflow-providers-papermill" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_papermill-{{ version }}.tar.gz
  sha256: 0b5f827bef252773374ce82b051b5d902157b99dd1bb58bc107e5980d3b0a187

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow >=2.5.0
    - ipykernel
    - papermill >=1.2.1
    # papermill[all]
    - azure-datalake-store >=0.0.30
    - azure-storage-blob >=12.1.0
    - requests >=2.21.0
    - gcsfs >=0.2.0
    - pyarrow
    - boto3

    - scrapbook
    # scrapbook[all] just requires papermill[all] so we're good

test:
  imports:
    - airflow.providers.papermill
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-papermill for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/papermill/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-papermill/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
